#FMC LPC MISC

set_property -dict "PACKAGE_PIN J22 IOSTANDARD LVCMOS25" [get_ports FMC_PRSNT_M2C_L]
set_property -dict "PACKAGE_PIN H29 IOSTANDARD LVCMOS25" [get_ports FMC_PG_C2M]

#FMC LPC GBTCLK
set_property PACKAGE_PIN N7 [get_ports FMC_GBTCLK0_M2C_C_N]
set_property PACKAGE_PIN N8 [get_ports FMC_GBTCLK0_M2C_C_P]
#FMC LPC DP
set_property PACKAGE_PIN F1 [get_ports FMC_DP0_C2M_N]
set_property PACKAGE_PIN F2 [get_ports FMC_DP0_C2M_P]
set_property PACKAGE_PIN F5 [get_ports FMC_DP0_M2C_N]
set_property PACKAGE_PIN F6 [get_ports FMC_DP0_M2C_P]
#FMC LPC CLK
set_property -dict "PACKAGE_PIN AG23 IOSTANDARD LVCMOS25" [get_ports FMC_CLK0_M2C_N]
set_property -dict "PACKAGE_PIN AF22 IOSTANDARD LVCMOS25" [get_ports FMC_CLK0_M2C_P]
set_property -dict "PACKAGE_PIN AH29 IOSTANDARD LVCMOS25" [get_ports FMC_CLK1_M2C_N]
set_property -dict "PACKAGE_PIN AG29 IOSTANDARD LVCMOS25" [get_ports FMC_CLK1_M2C_P]

#FMC LPC LA
set_property -dict "PACKAGE_PIN AE24 IOSTANDARD LVCMOS25" [get_ports FMC_LA00_CC_N]
set_property -dict "PACKAGE_PIN AD23 IOSTANDARD LVCMOS25" [get_ports FMC_LA00_CC_P]
set_property -dict "PACKAGE_PIN AF23 IOSTANDARD LVCMOS25" [get_ports FMC_LA01_CC_N]
set_property -dict "PACKAGE_PIN AE23 IOSTANDARD LVCMOS25" [get_ports FMC_LA01_CC_P]
set_property -dict "PACKAGE_PIN AF21 IOSTANDARD LVCMOS25" [get_ports FMC_LA02_N]
set_property -dict "PACKAGE_PIN AF20 IOSTANDARD LVCMOS25" [get_ports FMC_LA02_P]
set_property -dict "PACKAGE_PIN AH20 IOSTANDARD LVCMOS25" [get_ports FMC_LA03_N]
set_property -dict "PACKAGE_PIN AG20 IOSTANDARD LVCMOS25" [get_ports FMC_LA03_P]
set_property -dict "PACKAGE_PIN AJ21 IOSTANDARD LVCMOS25" [get_ports FMC_LA04_N]
set_property -dict "PACKAGE_PIN AH21 IOSTANDARD LVCMOS25" [get_ports FMC_LA04_P]
set_property -dict "PACKAGE_PIN AH22 IOSTANDARD LVCMOS25" [get_ports FMC_LA05_N]
set_property -dict "PACKAGE_PIN AG22 IOSTANDARD LVCMOS25" [get_ports FMC_LA05_P]
set_property -dict "PACKAGE_PIN AK21 IOSTANDARD LVCMOS25" [get_ports FMC_LA06_N]
set_property -dict "PACKAGE_PIN AK20 IOSTANDARD LVCMOS25" [get_ports FMC_LA06_P]
set_property -dict "PACKAGE_PIN AH25 IOSTANDARD LVCMOS25" [get_ports FMC_LA07_N]
set_property -dict "PACKAGE_PIN AG25 IOSTANDARD LVCMOS25" [get_ports FMC_LA07_P]
set_property -dict "PACKAGE_PIN AJ23 IOSTANDARD LVCMOS25" [get_ports FMC_LA08_N]
set_property -dict "PACKAGE_PIN AJ22 IOSTANDARD LVCMOS25" [get_ports FMC_LA08_P]
set_property -dict "PACKAGE_PIN AK24 IOSTANDARD LVCMOS25" [get_ports FMC_LA09_N]
set_property -dict "PACKAGE_PIN AK23 IOSTANDARD LVCMOS25" [get_ports FMC_LA09_P]
set_property -dict "PACKAGE_PIN AK25 IOSTANDARD LVCMOS25" [get_ports FMC_LA10_N]
set_property -dict "PACKAGE_PIN AJ24 IOSTANDARD LVCMOS25" [get_ports FMC_LA10_P]
set_property -dict "PACKAGE_PIN AF25 IOSTANDARD LVCMOS25" [get_ports FMC_LA11_N]
set_property -dict "PACKAGE_PIN AE25 IOSTANDARD LVCMOS25" [get_ports FMC_LA11_P]
set_property -dict "PACKAGE_PIN AB20 IOSTANDARD LVCMOS25" [get_ports FMC_LA12_N]
set_property -dict "PACKAGE_PIN AA20 IOSTANDARD LVCMOS25" [get_ports FMC_LA12_P]
set_property -dict "PACKAGE_PIN AC25 IOSTANDARD LVCMOS25" [get_ports FMC_LA13_N]
set_property -dict "PACKAGE_PIN AB24 IOSTANDARD LVCMOS25" [get_ports FMC_LA13_P]
set_property -dict "PACKAGE_PIN AE21 IOSTANDARD LVCMOS25" [get_ports FMC_LA14_N]
set_property -dict "PACKAGE_PIN AD21 IOSTANDARD LVCMOS25" [get_ports FMC_LA14_P]
set_property -dict "PACKAGE_PIN AD24 IOSTANDARD LVCMOS25" [get_ports FMC_LA15_N]
set_property -dict "PACKAGE_PIN AC24 IOSTANDARD LVCMOS25" [get_ports FMC_LA15_P]
set_property -dict "PACKAGE_PIN AD22 IOSTANDARD LVCMOS25" [get_ports FMC_LA16_N]
set_property -dict "PACKAGE_PIN AC22 IOSTANDARD LVCMOS25" [get_ports FMC_LA16_P]
set_property -dict "PACKAGE_PIN AC27 IOSTANDARD LVCMOS25" [get_ports FMC_LA17_CC_N]
set_property -dict "PACKAGE_PIN AB27 IOSTANDARD LVCMOS25" [get_ports FMC_LA17_CC_P]
set_property -dict "PACKAGE_PIN AD28 IOSTANDARD LVCMOS25" [get_ports FMC_LA18_CC_N]
set_property -dict "PACKAGE_PIN AD27 IOSTANDARD LVCMOS25" [get_ports FMC_LA18_CC_P]
set_property -dict "PACKAGE_PIN AK26 IOSTANDARD LVCMOS25" [get_ports FMC_LA19_N]
set_property -dict "PACKAGE_PIN AJ26 IOSTANDARD LVCMOS25" [get_ports FMC_LA19_P]
set_property -dict "PACKAGE_PIN AF27 IOSTANDARD LVCMOS25" [get_ports FMC_LA20_N]
set_property -dict "PACKAGE_PIN AF26 IOSTANDARD LVCMOS25" [get_ports FMC_LA20_P]
set_property -dict "PACKAGE_PIN AG28 IOSTANDARD LVCMOS25" [get_ports FMC_LA21_N]
set_property -dict "PACKAGE_PIN AG27 IOSTANDARD LVCMOS25" [get_ports FMC_LA21_P]
set_property -dict "PACKAGE_PIN AK28 IOSTANDARD LVCMOS25" [get_ports FMC_LA22_N]
set_property -dict "PACKAGE_PIN AJ27 IOSTANDARD LVCMOS25" [get_ports FMC_LA22_P]
set_property -dict "PACKAGE_PIN AH27 IOSTANDARD LVCMOS25" [get_ports FMC_LA23_N]
set_property -dict "PACKAGE_PIN AH26 IOSTANDARD LVCMOS25" [get_ports FMC_LA23_P]
set_property -dict "PACKAGE_PIN AH30 IOSTANDARD LVCMOS25" [get_ports FMC_LA24_N]
set_property -dict "PACKAGE_PIN AG30 IOSTANDARD LVCMOS25" [get_ports FMC_LA24_P]
set_property -dict "PACKAGE_PIN AD26 IOSTANDARD LVCMOS25" [get_ports FMC_LA25_N]
set_property -dict "PACKAGE_PIN AC26 IOSTANDARD LVCMOS25" [get_ports FMC_LA25_P]
set_property -dict "PACKAGE_PIN AK30 IOSTANDARD LVCMOS25" [get_ports FMC_LA26_N]
set_property -dict "PACKAGE_PIN AK29 IOSTANDARD LVCMOS25" [get_ports FMC_LA26_P]
set_property -dict "PACKAGE_PIN AJ29 IOSTANDARD LVCMOS25" [get_ports FMC_LA27_N]
set_property -dict "PACKAGE_PIN AJ28 IOSTANDARD LVCMOS25" [get_ports FMC_LA27_P]
set_property -dict "PACKAGE_PIN AF30 IOSTANDARD LVCMOS25" [get_ports FMC_LA28_N]
set_property -dict "PACKAGE_PIN AE30 IOSTANDARD LVCMOS25" [get_ports FMC_LA28_P]
set_property -dict "PACKAGE_PIN AF28 IOSTANDARD LVCMOS25" [get_ports FMC_LA29_N]
set_property -dict "PACKAGE_PIN AE28 IOSTANDARD LVCMOS25" [get_ports FMC_LA29_P]
set_property -dict "PACKAGE_PIN AB30 IOSTANDARD LVCMOS25" [get_ports FMC_LA30_N]
set_property -dict "PACKAGE_PIN AB29 IOSTANDARD LVCMOS25" [get_ports FMC_LA30_P]
set_property -dict "PACKAGE_PIN AE29 IOSTANDARD LVCMOS25" [get_ports FMC_LA31_N]
set_property -dict "PACKAGE_PIN AD29 IOSTANDARD LVCMOS25" [get_ports FMC_LA31_P]
set_property -dict "PACKAGE_PIN AA30 IOSTANDARD LVCMOS25" [get_ports FMC_LA32_N]
set_property -dict "PACKAGE_PIN Y30 IOSTANDARD LVCMOS25" [get_ports FMC_LA32_P]
set_property -dict "PACKAGE_PIN AC30 IOSTANDARD LVCMOS25" [get_ports FMC_LA33_N]
set_property -dict "PACKAGE_PIN AC29 IOSTANDARD LVCMOS25" [get_ports FMC_LA33_P]

#FMC HPC LA
