set cfg_dict {
   CONFIG.identical_val_tx_line_rate       {2.5}
   CONFIG.gt0_val                          {true}
   CONFIG.gt0_val_drp_clock                {50}
   CONFIG.gt0_val_rx_refclk                {REFCLK0_Q0}
   CONFIG.gt0_val_tx_refclk                {REFCLK0_Q0}
   CONFIG.identical_val_tx_reference_clock {125.000}
   CONFIG.gt0_val_txbuf_en                 {true}
   CONFIG.gt0_val_rxbuf_en                 {true}
   CONFIG.gt0_val_port_rxslide             {false}
   CONFIG.gt0_usesharedlogic               {0}
   CONFIG.identical_val_rx_line_rate       {2.5}
   CONFIG.gt_val_tx_pll                    {CPLL}
   CONFIG.gt_val_rx_pll                    {CPLL}
   CONFIG.identical_val_tx_reference_clock {125.000}
   CONFIG.identical_val_rx_reference_clock {125.000}
   CONFIG.gt0_val_encoding                 {8B/10B}
   CONFIG.gt0_val_decoding                 {8B/10B}
   CONFIG.gt0_val_port_tx8b10ben           {false}
   CONFIG.gt0_val_tx_line_rate             {2.5}
   CONFIG.gt0_val_tx_data_width            {16}
   CONFIG.gt0_val_tx_int_datawidth         {20}
   CONFIG.gt0_val_tx_reference_clock       {125.000}
   CONFIG.gt0_val_rx_line_rate             {2.5}
   CONFIG.gt0_val_rx_data_width            {16}
   CONFIG.gt0_val_rx_int_datawidth         {20}
   CONFIG.gt0_val_rx_reference_clock       {125.000}
   CONFIG.gt0_val_cpll_fbdiv               {4}
   CONFIG.gt0_val_cpll_rxout_div           {2}
   CONFIG.gt0_val_cpll_txout_div           {2}
   CONFIG.gt0_val_tx_buffer_bypass_mode    {Auto}
   CONFIG.gt0_val_txoutclk_source          {false}
   CONFIG.gt0_val_rx_buffer_bypass_mode    {Auto}
   CONFIG.gt0_val_rxusrclk                 {RXOUTCLK}
   CONFIG.gt0_val_rxslide_mode             {OFF}
   CONFIG.gt0_val_port_txbufstatus         {true}
   CONFIG.gt0_val_port_rxbufstatus         {true}
   CONFIG.gt0_val_port_rxpmareset          {true}
   CONFIG.gt0_val_align_mcomma_det         {true}
   CONFIG.gt0_val_align_pcomma_det         {true}
   CONFIG.gt0_val_comma_preset             {User_defined}
   CONFIG.gt0_val_align_pcomma_value       {0101111100}
   CONFIG.gt0_val_align_mcomma_value       {1010000011}
   CONFIG.gt0_val_align_comma_enable       {0001111111}
   CONFIG.gt0_val_align_comma_double       {false}
   CONFIG.gt0_val_align_comma_word         {Two_Byte_Boundaries}
   CONFIG.gt0_val_port_rxpcommaalignen     {true}
   CONFIG.gt0_val_port_rxmcommaalignen     {true}
   CONFIG.gt0_val_port_rxbyteisaligned     {true}
   CONFIG.gt0_val_dfe_mode                 {LPM-Auto}
   CONFIG.gt0_val_rx_termination_voltage   {Programmable}
   CONFIG.gt0_val_rx_cm_trim               {800}
   CONFIG.gt0_val_port_rxdfereset          {true}
   CONFIG.gt0_val_pd_trans_time_to_p2      {100}
   CONFIG.gt0_val_pd_trans_time_from_p2    {60}
   CONFIG.gt0_val_pd_trans_time_non_p2     {25}
}
