create_ip -name gtwizard -vendor xilinx.com -library ip -version 3.6 -module_name evr_gt

set_property -dict {
	CONFIG.advanced_clocking {false}
	CONFIG.example_chipscope {0}
	CONFIG.gt0_pll0_fbdiv {1}
	CONFIG.gt0_pll0_fbdiv_45 {4}
	CONFIG.gt0_pll0_refclk_div {1}
	CONFIG.gt0_pll0_rxout_div {1}
	CONFIG.gt0_pll0_txout_div {1}
	CONFIG.gt0_pll1_fbdiv {1}
	CONFIG.gt0_pll1_fbdiv_45 {4}
	CONFIG.gt0_pll1_refclk_div {1}
	CONFIG.gt0_pll1_rxout_div {1}
	CONFIG.gt0_pll1_txout_div {1}
	CONFIG.gt0_uselabtools {false}
	CONFIG.gt0_usesharedlogic {0}
	CONFIG.gt0_val {false}
	CONFIG.gt0_val_agc_mode {Auto}
	CONFIG.gt0_val_align_comma_double {false}
	CONFIG.gt0_val_align_comma_enable {1111111111}
	CONFIG.gt0_val_align_comma_word {Two_Byte_Boundaries}
	CONFIG.gt0_val_align_mcomma_det {true}
	CONFIG.gt0_val_align_mcomma_value {1010000011}
	CONFIG.gt0_val_align_pcomma_det {true}
	CONFIG.gt0_val_align_pcomma_value {0101111100}
	CONFIG.gt0_val_cb {false}
	CONFIG.gt0_val_cc {false}
	CONFIG.gt0_val_cc_seq_periodicity {5000}
	CONFIG.gt0_val_clk_cor_seq_1_1 {00000000}
	CONFIG.gt0_val_clk_cor_seq_1_2 {00000000}
	CONFIG.gt0_val_clk_cor_seq_1_3 {00000000}
	CONFIG.gt0_val_clk_cor_seq_1_4 {00000000}
	CONFIG.gt0_val_clk_cor_seq_2_1 {00000000}
	CONFIG.gt0_val_clk_cor_seq_2_2 {00000000}
	CONFIG.gt0_val_clk_cor_seq_2_3 {00000000}
	CONFIG.gt0_val_clk_cor_seq_2_4 {00000000}
	CONFIG.gt0_val_clk_cor_seq_len {1}
	CONFIG.gt0_val_comma_preset {K28.5}
	CONFIG.gt0_val_cpll_fbdiv {4}
	CONFIG.gt0_val_cpll_fbdiv_45 {5}
	CONFIG.gt0_val_cpll_refclk_div {1}
	CONFIG.gt0_val_cpll_rxout_div {2}
	CONFIG.gt0_val_cpll_txout_div {2}
	CONFIG.gt0_val_dec_mcomma_detect {true}
	CONFIG.gt0_val_dec_pcomma_detect {true}
	CONFIG.gt0_val_dec_valid_comma_only {true}
	CONFIG.gt0_val_decoding {8B/10B}
	CONFIG.gt0_val_dfe_mode {LPM-Auto}
	CONFIG.gt0_val_drp {true}
	CONFIG.gt0_val_drp_clock {125}
	CONFIG.gt0_val_max_cb_level {7}
	CONFIG.gt0_val_no_rx {false}
	CONFIG.gt0_val_no_tx {true}
	CONFIG.gt0_val_oob {false}
	CONFIG.gt0_val_port_rxcharisk {true}
	CONFIG.gt0_val_port_rxdfereset {true}
	CONFIG.gt0_val_port_rxelecidle {true}
	CONFIG.gt0_val_port_rxoutclk {true}
	CONFIG.gt0_val_port_rxpmareset {true}
	CONFIG.gt0_val_port_rxslide {true}
	CONFIG.gt0_val_port_txoutclk {true}
	CONFIG.gt0_val_ppm_offset {100}
	CONFIG.gt0_val_prbs_detector {false}
	CONFIG.gt0_val_protocol_file {Start_from_scratch}
	CONFIG.gt0_val_qpll_fbdiv {16}
	CONFIG.gt0_val_qpll_refclk_div {1}
	CONFIG.gt0_val_rx_buffer_bypass_mode {Auto}
	CONFIG.gt0_val_rx_cm_trim {800}
	CONFIG.gt0_val_rx_data_width {16}
	CONFIG.gt0_val_rx_equalizer {false}
	CONFIG.gt0_val_rx_int_datawidth {20}
	CONFIG.gt0_val_rx_line_rate {2.5}
	CONFIG.gt0_val_rx_refclk {REFCLK0_Q0}
	CONFIG.gt0_val_rx_reference_clock {125.000}
	CONFIG.gt0_val_rx_termination_voltage {Programmable}
	CONFIG.gt0_val_rxbuf_en {false}
	CONFIG.gt0_val_rxcomma_deten {true}
	CONFIG.gt0_val_rxoutclk_source {false}
	CONFIG.gt0_val_rxprbs_err_loopback {false}
	CONFIG.gt0_val_rxslide_mode {PCS}
	CONFIG.gt0_val_rxusrclk {RXOUTCLK}
	CONFIG.gt0_val_sata_e_idle_val {4}
	CONFIG.gt0_val_sata_rx_burst_val {4}
	CONFIG.gt0_val_tx_buffer_bypass_mode {Auto}
	CONFIG.gt0_val_tx_data_width {20}
	CONFIG.gt0_val_tx_int_datawidth {20}
	CONFIG.gt0_val_tx_line_rate {2.5}
	CONFIG.gt0_val_tx_refclk {REFCLK0_Q0}
	CONFIG.gt0_val_tx_reference_clock {125.000}
	CONFIG.gt0_val_txbuf_en {true}
	CONFIG.gt0_val_txdiff_emph_mode {Custom}
	CONFIG.gt0_val_txdiffctrl {false}
	CONFIG.gt0_val_txmaincursor {false}
	CONFIG.gt0_val_txoutclk_source {false}
	CONFIG.gt0_val_txpostcursor {false}
	CONFIG.gt0_val_txprecursor {false}
	CONFIG.gt0_val_txusrclk {TXOUTCLK}
	CONFIG.gt2_val {true}
	CONFIG.gt2_val_rx_refclk {REFCLK0_Q0}
	CONFIG.gt2_val_tx_refclk {REFCLK0_Q0}
	CONFIG.gt_column {right_column}
	CONFIG.gt_row {bottom_row}
	CONFIG.gt_type {GTX}
	CONFIG.gt_val_drp {false}
	CONFIG.gt_val_drp_clock {60}
	CONFIG.gt_val_extended_timeout {false}
	CONFIG.gt_val_rx_pll {CPLL}
	CONFIG.gt_val_tx_pll {CPLL}
	CONFIG.gtz0_val_data_width {160}
	CONFIG.identical_config {true}
	CONFIG.identical_protocol_file {Start_from_scratch}
	CONFIG.identical_val_no_rx {false}
	CONFIG.identical_val_no_tx {true}
	CONFIG.identical_val_rx_line_rate {2.5}
	CONFIG.identical_val_rx_reference_clock {125.000}
	CONFIG.identical_val_tx_line_rate {2.5}
	CONFIG.identical_val_tx_reference_clock {125.000}
} [get_ips evr_gt]

generate_target all [get_files  evr_gt.xci]
