create_ip -name gtwizard -vendor xilinx.com -library ip -version 3.6 -module_name evr_gt

set_property -dict {
    CONFIG.Component_Name {evr_gt}
    CONFIG.identical_val_tx_line_rate {2.5}
    CONFIG.identical_val_no_tx {true}
    CONFIG.identical_val_rx_line_rate {2.5}
    CONFIG.advanced_clocking {false}
    CONFIG.gt0_val_rx_data_width {16}
    CONFIG.gt0_val_decoding {8B/10B}
    CONFIG.gt0_val_drp_clock {100}
    CONFIG.gt0_val_rxbuf_en {false}
    CONFIG.gt0_val_port_rxslide {false}
    CONFIG.gt0_usesharedlogic {1}
    CONFIG.identical_val_rx_line_rate {2.5}
    CONFIG.gt_val_tx_pll {CPLL}
    CONFIG.gt0_val_tx_refclk {REFCLK1_Q0}
    CONFIG.gt_val_rx_pll {CPLL}
    CONFIG.gt0_val_rx_refclk {REFCLK1_Q0}
    CONFIG.gt1_val_tx_refclk {REFCLK1_Q0}
    CONFIG.gt1_val_rx_refclk {REFCLK1_Q0}
    CONFIG.gt2_val_tx_refclk {REFCLK1_Q0}
    CONFIG.gt2_val_rx_refclk {REFCLK1_Q0}
    CONFIG.gt3_val_tx_refclk {REFCLK1_Q0}
    CONFIG.gt3_val_rx_refclk {REFCLK1_Q0}
    CONFIG.gt4_val_tx_refclk {REFCLK1_Q1}
    CONFIG.gt4_val_rx_refclk {REFCLK1_Q1}
    CONFIG.gt5_val_tx_refclk {REFCLK1_Q1}
    CONFIG.gt5_val_rx_refclk {REFCLK1_Q1}
    CONFIG.gt6_val_tx_refclk {REFCLK1_Q1}
    CONFIG.gt6_val_rx_refclk {REFCLK1_Q1}
    CONFIG.gt7_val_tx_refclk {REFCLK1_Q1}
    CONFIG.gt7_val_rx_refclk {REFCLK1_Q1}
    CONFIG.gt8_val_tx_refclk {REFCLK1_Q2}
    CONFIG.gt8_val_rx_refclk {REFCLK1_Q2}
    CONFIG.gt9_val_tx_refclk {REFCLK1_Q2}
    CONFIG.gt9_val_rx_refclk {REFCLK1_Q2}
    CONFIG.gt10_val_tx_refclk {REFCLK1_Q2}
    CONFIG.gt10_val_rx_refclk {REFCLK1_Q2}
    CONFIG.gt11_val_tx_refclk {REFCLK1_Q2}
    CONFIG.gt11_val_rx_refclk {REFCLK1_Q2}
    CONFIG.gt12_val_tx_refclk {REFCLK1_Q3}
    CONFIG.gt12_val_rx_refclk {REFCLK1_Q3}
    CONFIG.gt13_val_tx_refclk {REFCLK1_Q3}
    CONFIG.gt13_val_rx_refclk {REFCLK1_Q3}
    CONFIG.gt14_val_tx_refclk {REFCLK1_Q3}
    CONFIG.gt14_val_rx_refclk {REFCLK1_Q3}
    CONFIG.gt15_val_tx_refclk {REFCLK1_Q3}
    CONFIG.gt15_val_rx_refclk {REFCLK1_Q3}
    CONFIG.identical_val_tx_reference_clock {156.250}
    CONFIG.identical_val_rx_reference_clock {156.250}
    CONFIG.gt0_val_no_tx {true}
    CONFIG.gt0_val_tx_line_rate {2.5}
    CONFIG.gt0_val_tx_data_width {20}
    CONFIG.gt0_val_encoding {None}
    CONFIG.gt0_val_tx_int_datawidth {20}
    CONFIG.gt0_val_tx_reference_clock {156.250}
    CONFIG.gt0_val_rx_line_rate {2.5}
    CONFIG.gt0_val_rx_int_datawidth {20}
    CONFIG.gt0_val_rx_reference_clock {156.250}
    CONFIG.gt0_val_cpll_fbdiv_45 {4}
    CONFIG.gt0_val_port_rxcharisk {true}
    CONFIG.gt0_val_rx_buffer_bypass_mode {Auto}
    CONFIG.gt0_val_rxusrclk {RXOUTCLK}
    CONFIG.gt0_val_comma_preset {K28.5}
    CONFIG.gt0_val_align_comma_word {Any_Byte_Boundary}
    CONFIG.gt0_val_dfe_mode {LPM-Auto}
    CONFIG.gt0_val_rx_termination_voltage {Programmable}
    CONFIG.gt0_val_rx_cm_trim {800}
    CONFIG.gt0_val_clk_cor_seq_1_1 {00000000}
    CONFIG.gt0_val_clk_cor_seq_1_2 {00000000}
    CONFIG.gt0_val_clk_cor_seq_1_3 {00000000}
    CONFIG.gt0_val_clk_cor_seq_1_4 {00000000}
    CONFIG.gt0_val_clk_cor_seq_2_1 {00000000}
    CONFIG.gt0_val_clk_cor_seq_2_2 {00000000}
    CONFIG.gt0_val_clk_cor_seq_2_3 {00000000}
    CONFIG.gt0_val_clk_cor_seq_2_4 {00000000}
    CONFIG.gt0_val_rxslide_mode {OFF}
} [get_ips evr_gt]

generate_target all [get_files  evr_gt.xci]
