name: Bedrock documentation

on: [push, pull_request]

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as
    # they'll be run by the push to the branch. Without this if check,
    # checks are duplicated since internal PRs match both the push and
    # pull_request events.
    if: >
      github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.8'

      - name: Install python PIP packages
        run: |
          python -m pip install \
                sphinx==5.0.2 \
                sphinx_rtd_theme \
                numpy m2r2==0.3.2

      - name: Install documentation tools
        run: |
          sudo apt-get update
          sudo apt-get -y install make \
                          imagemagick ghostscript \
                          iverilog xvfb gtkwave \
                          texlive-binaries
          sudo sed -i -e '/pattern="PS"/ s/rights=".*" pattern=/rights="read|write" pattern=/g' \
                      -e '/pattern="PDF"/ s/rights=".*" pattern=/rights="read|write" pattern=/g' \
                      -e '/pattern="EPS"/ s/rights=".*" pattern=/rights="read|write" pattern=/g' \
                      -e '/<\/policymap>/i \  <policy domain="coder" rights="read|write" pattern="{GIF,JPEG,PNG,WEBP}" \/>' /etc/ImageMagick-*/policy.xml

      - name: Build sphinx docs
        run: |
          make -C doc html

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/_build/html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: badger-doc
          path: badger/doc/*.svg
