name: Bedrock documentation

on: [push, pull_request]

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as
    # they'll be run by the push to the branch. Without this if check,
    # checks are duplicated since internal PRs match both the push and
    # pull_request events.
    if: >
      github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'

      - name: Install documentation tools
        run: |
          sudo apt-get update
          sudo apt-get -y install make xvfb pandoc xcircuit python3-sphinx

      - name: Build diagrams
        run: |
          make -C badger/doc

      - name: Build sphinx docs
        run: |
          make -C doc html

      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/_build/html

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: badger-doc
          path: badger/doc/*.svg
