leep_test:
  stage: test
  before_script:
    - python3 -m pip \
        build \
        hatch \
        hatchling
    - cd projects/common/leep
  script:
    - python -m build -v
    - hatch test -v
