marble_sim:
  extends: .build-matrix
  image: $IMAGE
  stage: test
  script:
    - make -C projects/test_marble_family all net_slave_check
    - make -C projects/test_marble_family/pps_lock

marble_i2c_check:
  extends: .build-matrix
  image: $IMAGE
  stage: test
  script:
    - make -C projects/test_marble_family/i2c tests

.bitgen:
  stage: synthesis
  before_script:
    - cd projects/test_marble_family && ls /non-free
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 2 days

.synth_base:
  extends:
    - .build-matrix
    - .bitgen
  image: $IMAGE
  script:
    - PATH=$XILINX_VIVADO/bin:$PATH make CONFIG=${CONFIG} bit
  artifacts:
    paths:
      - projects/test_marble_family/marble*.bit
      - projects/test_marble_family/vivado.log
      - projects/test_marble_family/_xilinx/${CONFIG}.runs/*.rpt
      - projects/test_marble_family/_xilinx/${CONFIG}.runs/synth_1/marble_top_*.rpt
      - projects/test_marble_family/_xilinx/${CONFIG}.runs/impl_1/marble_top_*.rpt

marble_mini_synth:
  extends: .synth_base
  variables:
    CONFIG: marblemini

marble_v2_synth:
  extends: .synth_base
  variables:
    CONFIG: marble

marble_fiber_synth:
  extends: .synth_base
  variables:
    CONFIG: marble_fiber

.run_base:
  extends: .build-matrix
  image: $IMAGE
  stage: program
  tags:
    - deploy
  before_script:
    - cd projects/test_marble_family && ln -s ${CONFIG}.*.bit ${CONFIG}.bit
  script:
    - make CONFIG=${CONFIG} hwload ${SERIAL_ARG} && sleep 8 && make CONFIG=${CONFIG} hwtest ${SERIAL_ARG}
    - if [ -n "$RUN_I2C" ]; then make -C i2c live_oneshot ${SERIAL_ARG}; fi

marble_mini_run:
  extends: .run_base
  dependencies:
    - marble_mini_synth
  environment: hw_marble_mini
  resource_group: hw_marble_mini
  variables:
    CONFIG: marblemini
    SERIAL_ARG: ""
    RUN_I2C: ""

marble_run:
  extends: .run_base
  dependencies:
    - marble_v2_synth
  environment: hw_marble
  resource_group: hw_marble
  variables:
    CONFIG: marble
    SERIAL_ARG: "SERIAL=39"
    RUN_I2C: "true"

marble_fiber_run:
  extends: .run_base
  dependencies:
    - marble_fiber_synth
  environment: hw_marble
  resource_group: hw_marble
  variables:
    CONFIG: marble_fiber
    SERIAL_ARG: "SERIAL=39"
    RUN_I2C: "true"
