# grab-bag of other Verilog/HDL simulation tests

cordic_test:
  extends: .build-matrix
  image: $IMAGE
  before_script:
    - cd cordic && make clean
  stage: test
  script:
    - make all

freq_demo:
  extends: .build-matrix
  image: $IMAGE
  stage: test
  script:
    - make -C homeless/freq_demo
    - make -C homeless all checks

peripheral_test:
  extends: .build-matrix
  image: $IMAGE
  stage: test
  script:
    - make -C peripheral_drivers
    - make -C peripheral_drivers/idelay_scanner
    - make -C peripheral_drivers/ds1822
    - make -C peripheral_drivers/i2cbridge

xilinx_test:
  extends: .build-matrix
  image: $IMAGE
  stage: test
  script:
    - make -C fpga_family/xilinx
